name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'
    - name: Install test dependencies
      run: pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
    - name: Build
      run: cargo build --all-features --all-targets
    - name: Compile test programs
      run: make cairo_test_programs
    - name: Compile proof programs
      run: make cairo_proof_programs
    - name: Compile benchmark programs
      run: make cairo_bench_programs
    - name: Run cairo-lang on tests
      run: cairo_trace
    - name: Run cairo-rs on tests
      run: rs_trace
    - name: Compare trace
      run: make compare_trace
    - name: Compare memory
      run: make compare_memory
